- name: Latest container is pulled
  shell: sudo docker pull 192.168.50.91:5000/busybox-go-web-docker
  tags: [busybox-go-web-docker]

- name: Container is absent
  docker_container:
    image=192.168.50.91:5000/busybox-go-web-docker
    name=books-service
    state=absent
  tags: [books-service]

- name: Container is running
  docker_container:
    name=busybox-go-web-docker
    image=192.168.50.91:5000/busybox-go-web-docker
    ports=9001:8080
    state=started
  tags: [busybox-go-web-docker]
