- name: ensure required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
- name: add docker ce repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  register: docker_yum_repo
- name: make yum cache fast
  shell: yum makecache fast
  when: docker_yum_repo.changed
- name: install docker ce
  yum:
    name: "docker-ce.x86_64"
    state: present
  notify: restart docker
