- name: ensure required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
- name: add docker ce repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  register: docker_yum_repo
- name: make yum cache fast
  shell: yum makecache fast
  when: docker_yum_repo.changed
- name: install python-pip
  yum:
    name: "python-pip"
    state: present
- name: Install docker-compose
  pip:
    name: docker-compose
- name: install docker ce
  yum:
    name: "docker-ce.x86_64"
    state: present
  notify: restart docker
- name: create sysconfig file
  template:
    src: sysconfig.j2
    dest: /etc/sysconfig/docker
- name: start and enable docker
  service:
    name: docker
    state: started
    enabled: yes
